version: '3'

services:
  mysql:
    hostname: "mysql"
    restart: unless-stopped
    image: mysql:5.7
    network_mode: bridge
    ports:
      - "3306:3306"
    env_file:
      - variables.env
    volumes:
      - ./etc/mysql/conf.d/:/etc/mysql/conf.d/
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql

  phalcon-apache:
    hostname: "a2php"
    restart: unless-stopped
    image: lavaimagem/phalcon:apache2-php7.4
    network_mode: bridge
    ports:
        - "80:80"
    links:
      - "mysql"
    depends_on:
      - "mysql"
    env_file:
      - variables.env
    volumes:
      - ./www:/var/www

volumes:
  mysql:
    driver: local
  phalcon-apache:
    driver: local
